### ISSUE TITLE
blender 2.8?

### ISSUE THREAD

**Issue by macduff111** [krljg/lsystem#1]
hi this looks really good, but doesn't appear to work for blender 2.8. should it? if not, any plans to make it compatible?

**Comment by krljg** [comment]
Hi,

I have only used it in blender 2.79b. No real support for 2.8 yet. It'll probably take me a couple of weeks to make it compatible, but yeah I'll give it a try.

**Comment by krljg** [comment]
It seems to work now in blender 2.8.

**Comment by macduff111** [comment]
great -thanks
