### ISSUE TITLE
The cross-section of the branch is square. Is it possible to change it to circular cross-section?

### ISSUE THREAD

**Issue by rqwang** [krljg/lsystem#7]

**Comment by krljg** [comment]
Yeah, you can try using different "pens". Either "subsurf" or use "skin" and then add a subdivision surface modifier manually. Alternatively you can use a cylinder with "cyl16".

So for an example ruleset:
start rule:  p(subsurf)X
rule 0: [-FX][FX]

**Comment by rqwang** [comment]
Thanks for the solution. I could generate a structure as in the figure. but it seems to have a hole at the branching. Is there a solution to fill the hole? The code is this:
%%%%%%%%%%%%%%%%%%%%
import lsystem.exec
exec = lsystem.exec.Exec()
exec.define("r1", "0.9")
exec.define("a0", "50")
exec.define("d", "130")
exec.define("wr", "0.707")
exec.set_axiom("p(subsurf)A(1,0.25)")
exec.add_rule("A(l,w)", "¤(w)F(l)[&(a0)B(mul(l,r1),mul(w,wr))]/(d)A(mul(l,r1),mul(w,wr))")
exec.add_rule("B(l,w)", "¤(w)F(l)[-(a0)$C(mul(l,r1),mul(w,wr))]C(mul(l,r1),mul(w,wr))")
exec.add_rule("C(l,w)", "¤(w)F(l)[+(a0)$B(mul(l,r1),mul(w,wr))]B(mul(l,r1),mul(w,wr))")
exec.exec(min_iterations=4)
%%%%%%%%%
![Screen Shot 2022-03-02 at 2 26 59 PM](https://user-images.githubusercontent.com/13221638/156434645-594d0ec4-7d21-41de-a726-51208482f534.png)

Thanks a lot.

**Comment by krljg** [comment]
Not sure why that happens but if you download the  latest now, you can try using p(curve) instead of p(subsurf).

You should then get something like this, no weird hole, and a circular cross section.
![image](https://user-images.githubusercontent.com/14252670/156843839-1d185e9c-d5a2-4f76-9cb6-d5e83c7e6da2.png)

**Comment by extro24** [comment]
Beautiful.

**Comment by krljg** [comment]
And now p(subsurf) should work better. The issue appears to be that "use_x_symmetry" was set to True by default when creating a new skin modifier.

![image](https://user-images.githubusercontent.com/14252670/156894497-77aa0a75-9a11-4e9a-95bf-339b8630574a.png)
