### ISSUE TITLE
Translating copied object

### ISSUE THREAD

**Issue by siadajpan** [krljg/lsystem#8]
Hi, I'm having some problems scaling and rotating the object that I've copied.
I have a model saved in a glb file, and I need to copy this object in couple places with rotation and scaling. 
I was trying: 
```
[:~(object_name)s(0.1,0.1,0.1);]
[:~(object_name)¤(0.1);]
[:~(object_name);s(0.1,0.1,0.1)]
[:/(355.3)^(17.5)~(object_name)s(0.01,0.01,0.01);]
```

But it's just copying the object to the cursor without scaling or rotating.

**Comment by siadajpan** [comment]
ok, I saw into the code and scaling of the copied object has #todo comment

**Comment by krljg** [comment]
The pull request is merged so I guess this is fixed.
